name: Test Run
on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Check branch name
        run: |
          if [ "${BRANCH_NAME}" == "master" ]; then
            export IMAGE_TAG="image-name:tag"
          else
            export IMAGE_TAG="image-name:tag-${BRANCH_NAME}"
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

          echo "The image tag used here is ${IMAGE_TAG}"
          
  
