name: Test Run
on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: Check branch name
        run: |
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "master"
          else
            echo "not master"
          fi
  
