name: Test Run
on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Prepare Image tags
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          if [ "${BRANCH_NAME}" == "master" ]; then
            export IMAGE_TAG="test-image:v1"
          else
            export IMAGE_TAG="test-image:v1-${BRANCH_NAME}"
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
      - name: Build platform specific Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${env.IMAGE_TAG}-amd64
          push: false
          file: Dockerfile
      - name: List Docker images
        run: |
          docker images
          
  
